# Generated by Django 6.0.3 on 2026-04-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_notice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_popup',
            field=models.BooleanField(default=False),
        ),
    ]
